# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitmaelumSuite < Formula
  desc "BitMaelum is an end-to-end email alternative"
  homepage "https://bitmaelum.com/"
  version "0.1.1-3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.1.1-3/bitmaelum-suite_0.1.1-3_darwin_x86_64.tar.gz"
    sha256 "561a3846781a4cca1fc1909906c2823b249896c661b5d956cc2f532b6f528f32"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.1.1-3/bitmaelum-suite_0.1.1-3_linux_x86_64.tar.gz"
    sha256 "dd661869e68ff0c61f729c52bbc050d5fa01283aff04355649ee897378c85a46"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.1.1-3/bitmaelum-suite_0.1.1-3_linux_arm64.tar.gz"
    sha256 "85b95597c33ff72ecf7a3d455dfe8594edca0088f7f6184d9d6b4ffd79a675fa"
  end

  def install
    bin.install "bitmaelum-suite"
  end
end
