# This file was generated by GoReleaser. DO NOT EDIT.
class BitmaelumSuite < Formula
  desc "BitMaelum is an end-to-end email alternative"
  homepage "https://bitmaelum.com/"
  version "0.0.11"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.0.11/bitmaelum-suite_0.0.11_darwin_x86_64.tar.gz"
    sha256 "e0d143e0c0fb6ef49118874cefa9b6fb2488ec56b4b3f7546bee06803cd6f819"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.0.11/bitmaelum-suite_0.0.11_linux_x86_64.tar.gz"
    sha256 "f644f4f802fb76ac04aaca0a5bebf654c16cc311db7b9303d5de12f0c0f138ad"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bitmaelum/bitmaelum-suite/releases/download/v0.0.11/bitmaelum-suite_0.0.11_linux_arm64.tar.gz"
    sha256 "22f03c6b466d8972a312794851df26ccb53b2d365b6d5a4288df6e1e99755155"
  end

  def install
    bin.install "bm-client"
    bin.install "bm-config"
    bin.install "bm-json"
    bin.install "bm-send"
    bin.install "bm-server"
  end
end
